server:
  port: 8084

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/test-api
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sys as sysdba
    password: admin
    driverClassName: oracle.jdbc.driver.OracleDriver

logging.group:
  tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
    
logging.level:
#  root: INFO
#  tomcat: WARN
#  oauth.demoproject: INFO
  web: trace
    