server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/test-api
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sys as sysdba
    password: admin
    driverClassName: oracle.jdbc.driver.OracleDriver
    
logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    